/*
 * Identity API specifications
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.6.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identity
// LookupHostResponse struct for LookupHostResponse
type LookupHostResponse struct {
	EntityId int64 `json:"entityId"`
	Guid string `json:"guid,omitempty"`
}
