/*
 * Identity API specifications
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.6.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identity
// ReRegisterResponse struct for ReRegisterResponse
type ReRegisterResponse struct {
	EntityId int64 `json:"entityId"`
	Guid string `json:"guid"`
	Warnings []string `json:"warnings,omitempty"`
}
