/*
 * Identity API specifications
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.6.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identity
// LookupRequest struct for LookupRequest
type LookupRequest struct {
	EntityName string `json:"entityName"`
}
