/*
 * Identity API specifications
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.6.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identity
// LookupHostRequest struct for LookupHostRequest
type LookupHostRequest struct {
	Fingerprint Fingerprint `json:"fingerprint"`
}
